# -*- coding: utf-8 -*-
"""MultiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7pCn3FACfz6aCy9oN-ALTUZNjM0tyCF
"""

import sqlite3
import os

os.makedirs("database", exist_ok=True)

DB_PATH = "database/city_risk.db"

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS issues (
    issue_id INTEGER PRIMARY KEY,
    title TEXT,
    category TEXT,
    status TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS issue_signals (
    issue_id INTEGER,
    population_affected INTEGER CHECK(population_affected >= 0),
    complaint_count INTEGER CHECK(complaint_count >= 0),
    safety_risk INTEGER CHECK(safety_risk IN (0,1)),
    legal_mandate INTEGER CHECK(legal_mandate IN (0,1)),
    estimated_cost INTEGER,   -- informational only
    FOREIGN KEY(issue_id) REFERENCES issues(issue_id) )
""")


conn.commit()
conn.close()

print(" Database created")

"""Defining city-level information, risk thresholds and defining how important each risk factor is"""

CITY_PROFILE = {
    "city_name": "Metroville",
    "population_range": (50_000, 5_000_000),
    "quarterly_budget_range": (5_000_000, 250_000_000)  # USD
}

# minimum conditions required for an issue to be treated as high risk.
RISK_THRESHOLDS = {
    "high_population": 100_000,
    # If an issue affects 100,000 or more people, it is considered high impact.
    "high_complaints": 75,
    # If 75 or more complaints are received, the issue is considered serious.
    "high_risk_score": 3
    # If the total risk score is 3 or higher, the issue is labeled HIGH RISK.
}

RISK_WEIGHTS = {
    "safety_risk": 3,
    # Safety issues (risk to life or injury) are very important, So they get 3 points.
    "legal_mandate": 3,
    # Issues required by law must be addressed urgently, So they also get 3 points
    "population_impact": 1,
    # Affecting many people is important, but less critical than safety, So it gets 1 point.
    "complaint_volume": 1
}

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

issues_data = [
    (1, "Major Water Pipeline Rupture", "Water", "OPEN"),
    (2, "Hospital Power Backup Failure", "Health", "OPEN"),
    (3, "Urban Flooding in Low-Lying Areas", "Disaster Management", "OPEN"),
    (4, "Pothole Complaints in Residential Zones", "Infrastructure", "OPEN"),
    (5, "Public Park Renovation Delay", "Recreation", "OPEN")
]

signals_data = [
    # issue_id, population, complaints, safety, legal, est_cost
    (1, 450_000, 1200, 1, 1, 45_000_000),
    (2, 180_000, 300, 1, 1, 12_000_000),
    (3, 600_000, 900, 1, 0, 60_000_000),
    (4, 80_000, 40, 0, 0, 4_000_000),
    (5, 15_000, 12, 0, 0, 2_500_000)
]

# Clear existing data to prevent IntegrityError on re-runs
cursor.execute("DELETE FROM issue_signals")
cursor.execute("DELETE FROM issues")

cursor.executemany(
    "INSERT INTO issues VALUES (?, ?, ?, ?)", issues_data
)

cursor.executemany(
    "INSERT INTO issue_signals VALUES (?, ?, ?, ?, ?, ?)", signals_data
)

conn.commit()
conn.close()

print(" Sample data inserted")

class HighRiskAssessmentAgent:
    """
    Agent responsible for identifying HIGH-RISK municipal issues
    based on safety, legal, population, and complaint signals.
    """

    def __init__(self, db_path):
        self.db_path = db_path

    def compute_risk_score(self, signal):
      score = 0

      if signal["safety_risk"]:
          score += RISK_WEIGHTS["safety_risk"]

      if signal["legal_mandate"]:
          score += RISK_WEIGHTS["legal_mandate"]

      if signal["population_affected"] >= RISK_THRESHOLDS["high_population"]:
          score += RISK_WEIGHTS["population_impact"]

      if signal["complaint_count"] >= RISK_THRESHOLDS["high_complaints"]:
          score += RISK_WEIGHTS["complaint_volume"]

      return score


    def fetch_open_issues(self):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("""
        SELECT
            i.issue_id,
            i.title,
            i.category,
            s.population_affected,
            s.complaint_count,
            s.safety_risk,
            s.legal_mandate,
            s.estimated_cost
        FROM issues i
        JOIN issue_signals s ON i.issue_id = s.issue_id
        WHERE i.status = 'OPEN'
        """)

        rows = cursor.fetchall()
        conn.close()
        return rows

    def system_context(self):
      return {
          "city": CITY_PROFILE["city_name"],
          "population_range": CITY_PROFILE["population_range"],
          "quarterly_budget_range": CITY_PROFILE["quarterly_budget_range"],
          "note": "Budget is informational only and not used for risk decisions"
      }


    def run(self):
        rows = self.fetch_open_issues()
        high_risk_issues = []

        for r in rows:
            signal = {
                "issue_id": r[0],
                "title": r[1],
                "category": r[2],
                "population_affected": r[3],
                "complaint_count": r[4],
                "safety_risk": bool(r[5]),
                "legal_mandate": bool(r[6]),
                "estimated_cost": r[7]

            }

            risk_score = self.compute_risk_score(signal)

            if risk_score >= RISK_THRESHOLDS["high_risk_score"]:

                high_risk_issues.append({
                    "issue_id": signal["issue_id"],
                    "title": signal["title"],
                    "category": signal["category"],
                    "risk_score": risk_score,
                    "risk_level": "HIGH",
                    "reasons": {
                        "safety_risk": signal["safety_risk"],
                        "legal_mandate": signal["legal_mandate"],
                        "high_population_impact":signal["population_affected"] >= RISK_THRESHOLDS["high_population"],
                        "high_complaints": signal["complaint_count"] >= RISK_THRESHOLDS["high_complaints"]
                    }
                })

        return {
      "system_context": self.system_context(),
      "high_risk_issues": high_risk_issues
}

agent = HighRiskAssessmentAgent(DB_PATH)

results = agent.run()

print("\nSYSTEM CONTEXT:")
for key, value in results["system_context"].items():
    print(f"  {key}: {value}")

print("\nHIGH-RISK ISSUES IDENTIFIED:")
if results["high_risk_issues"]:
    for issue in results["high_risk_issues"]:
        print(issue)
else:
    print("  No high-risk issues identified.")

"""The above system identifies high-risk city issues by analyzing safety, legal urgency, population impact, and citizen complaints, without letting budget constraints affect safety decisions."""

